In [72]:
import tensorflow as tf   
import numpy as np 
print(tf.__version__)
print(np.__version__)


2.9.2
1.22.3


In [73]:
# creating a tensor 

scalar = tf.constant(7)
scalar
# testing scalars


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [74]:
#checking the number of dimensions 
scalar.ndim
## this will show 0 becasue there are no dimensions in a scalar with only 1 dimension


0

In [75]:
vector = tf.constant([10,10])
vector 

#here we are making a vector with the 10 ad 10 compoenents then are printing the componenets

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [76]:
#checking the numeber of dimensions that are present in the vector

vector.ndim
# we are getting 1 as the number of dimensions because we see that there is only 1 dimension in a vector  with 2 compoenents 

1

In [77]:
matrix = tf.constant([[10,7],
                    [7,10]])
matrix
# creating a tensor matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [78]:
# we are now chekcing the number of dimensions
matrix.ndim
## notice we are getting 2 as the number of dimensions for a matrix 

2

In [79]:
# creating another matrix that has datatype defined 

matrix2 = tf.constant([[10.,7.],
                       [3.,2.],
                       [8.,9.]], dtype = tf.float16) # specifying the datat type 
matrix2
# initially we are printing out the number of shapes (rows, columns) and tehn the datat type which is float type in this canse )

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [80]:
# the numeber of dimensions of our matrix would be still 2 because it is the total number of elements in the shape matrix
matrix2.ndim

2

In [81]:
## a tensor hads 3 dimensions 
tensor = tf.constant([[[1,2,3,],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor
#now there is a new element in shape 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [82]:
tensor.ndim
#notice that the output is 3 becasue there are 3 dimensions in teh tensor 
# but in a tensor there can be n- dimensions 

3

In [83]:
# we are able to use tf.variable to create a tensor of the same
# we want to create teh same tensor as the tensor above 
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor,unchangable_tensor
#the output will be the same but the variable will be 0 in the changalbe tensor because we are able to change the variable  


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [84]:
# we want to change the element in the 0th posisiton 
# then we can use the .assign() function to change the value 
changable_tensor[0].assign(7)
changable_tensor

# now we have changed the value so the tensor reads [7,7]
# we are not able to change the values in the constant tensors 
#generally we want to use constant tensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [94]:
# creating random tensors 
# these are tensors tensors that are of abitrary size which contain random numbers 
# this might be done in the scenario of a neural netowrk it will initilize a neurla network with random number s and then as it learns it will change the random tensors in order to change the weightings 
with tf.device('/cpu:0'): randomtensor1 = tf.random.Generator.from_seed(7) # the seed for reproducibility 
randomtensor1 = randomtensor1.normal(shape=(3, 2))
randomtensor1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [98]:
with tf.device('/cpu:0'): randomtensor2 = tf.random.Generator.from_seed(7)
randomtensor2 = randomtensor2.normal(shape=(3,2)) # generates numbers fomr a normal distribution
randomtensor2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [96]:
randomtensor1 == randomtensor2
# now we are chekcing if 2 different tensors are equal 
# we can use the == operater to check this 
#wehn we set the seed we essetially modify the random numbers with the certain seed 
#if we change teh seed we will get different value 




<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [103]:
# how to shuffle the order of teh elements in a tensor
# shuffle tensor so that the inherent order doesnt affect the tensor 
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [8,9]],)
not_shuffled.ndim

2

In [105]:
not_shuffled



<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8,  9]], dtype=int32)>

In [127]:
tf.random.set_seed(42)# the operation level seed #now if we set the seed first and then we are going to affect the behaviour of the tensor so ts certain 
shuffled = tf.random.shuffle(not_shuffled, seed = 3) #this contains the operation level seed
shuffled
# shuffling the tensor along the first dimension
#what if we want to shuffle along the second dimension ?
# what happens when we shuffle seeds is that we are going to 
# if both the global and operation level seeds are set then theya re used in conjucntion 
# if we want our shuffled tensors we have to use the global level random seed 
# to make reproducable experiments we may use random seeds and set them to enable reproducable randomness 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  9],
       [ 3,  4]], dtype=int32)>

In [129]:
#numpy ones is a way to make tensors 
# we are able to use the tf.ones method to create a tensor that consisitas of all float type ones 
tf.ones([10,4])



<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [130]:
tf.zeros(shape = (3,4)) # passing in the shape as the rows adn columnsof the array that we want 
#very simialr to numpy so we are able to convert numpy arrays into tensorflow tensors 

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [133]:
#importing numpy and then coverting numpy arrays into tensorflow tensors 
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) # create a Numpy array between 1 and 25 
numpy_A # arrays are often noted with capital letters 


# X = tf.constant(some_matrix)
# y = tf.constnat(vector) # non-capital for vector 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)