In [3]:
import tensorflow as tf   
import numpy as np 
print(tf.__version__)
print(np.__version__)



2.9.2
1.22.3


In [2]:
# creating a tensor 

scalar = tf.constant(7)
scalar
# testing scalars


Metal device set to: 

2022-06-25 19:25:31.089771: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:305] Could not identify NUMA node of platform GPU ID 0, defaulting to 0. Your kernel may not have been built with NUMA support.
2022-06-25 19:25:31.090099: I tensorflow/core/common_runtime/pluggable_device/pluggable_device_factory.cc:271] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 0 MB memory) -> physical PluggableDevice (device: 0, name: METAL, pci bus id: <undefined>)


<tf.Tensor: shape=(), dtype=int32, numpy=7>

Apple M1 Pro

systemMemory: 16.00 GB
maxCacheSize: 5.33 GB



In [3]:
#checking the number of dimensions 
scalar.ndim
## this will show 0 becasue there are no dimensions in a scalar with only 1 dimension


0

In [4]:
vector = tf.constant([10,10])
vector 

#here we are making a vector with the 10 ad 10 compoenents then are printing the componenets

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
#checking the numeber of dimensions that are present in the vector

vector.ndim
# we are getting 1 as the number of dimensions because we see that there is only 1 dimension in a vector  with 2 compoenents 

1

In [6]:
matrix = tf.constant([[10,7],
                    [7,10]])
matrix
# creating a tensor matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# we are now chekcing the number of dimensions
matrix.ndim
## notice we are getting 2 as the number of dimensions for a matrix 

2

In [8]:
# creating another matrix that has datatype defined 

matrix2 = tf.constant([[10.,7.],
                       [3.,2.],
                       [8.,9.]], dtype = tf.float16) # specifying the datat type 
matrix2
# initially we are printing out the number of shapes (rows, columns) and tehn the datat type which is float type in this canse )

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [9]:
# the numeber of dimensions of our matrix would be still 2 because it is the total number of elements in the shape matrix
matrix2.ndim

2

In [10]:
## a tensor hads 3 dimensions 
tensor = tf.constant([[[1,2,3,],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor
#now there is a new element in shape 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [11]:
tensor.ndim
 

3

In [12]:
# we are able to use tf.variable to create a tensor of the same
# we want to create teh same tensor as the tensor above 
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor,unchangable_tensor
#the output will be the same but the variable will be 0 in the changalbe tensor because we are able to change the variable  


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# we want to change the element in the 0th posisiton 
# then we can use the .assign() function to change the value 
changable_tensor[0].assign(7)
changable_tensor

# now we have changed the value so the tensor reads [7,7]
# we are not able to change the values in the constant tensors 
#generally we want to use constant tensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [14]:
# creating random tensors 
# these are tensors tensors that are of abitrary size which contain random numbers 
# this might be done in the scenario of a neural netowrk it will initilize a neurla network with random number s and then as it learns it will change the random tensors in order to change the weightings 
with tf.device('/cpu:0'): randomtensor1 = tf.random.Generator.from_seed(7) # the seed for reproducibility 
randomtensor1 = randomtensor1.normal(shape=(3, 2))
randomtensor1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [15]:
with tf.device('/cpu:0'): randomtensor2 = tf.random.Generator.from_seed(7)
randomtensor2 = randomtensor2.normal(shape=(3,2)) # generates numbers fomr a normal distribution
randomtensor2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [16]:
randomtensor1 == randomtensor2
# now we are chekcing if 2 different tensors are equal 
# we can use the == operater to check this 
#wehn we set the seed we essetially modify the random numbers with the certain seed 
#if we change teh seed we will get different value 




<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [17]:
# how to shuffle the order of teh elements in a tensor
# shuffle tensor so that the inherent order doesnt affect the tensor 
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [8,9]],)
not_shuffled.ndim

2

In [18]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8,  9]], dtype=int32)>

In [19]:
tf.random.set_seed(42)# the operation level seed #now if we set the seed first and then we are going to affect the behaviour of the tensor so ts certain 
shuffled = tf.random.shuffle(not_shuffled, seed = 3) #this contains the operation level seed
shuffled
# shuffling the tensor along the first dimension
#what if we want to shuffle along the second dimension ?
# what happens when we shuffle seeds is that we are going to 
# if both the global and operation level seeds are set then theya re used in conjucntion 
# if we want our shuffled tensors we have to use the global level random seed 
# to make reproducable experiments we may use random seeds and set them to enable reproducable randomness 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  9],
       [ 3,  4]], dtype=int32)>

In [20]:
#numpy ones is a way to make tensors 
# we are able to use the tf.ones method to create a tensor that consisitas of all float type ones 
tf.ones([10,4])



<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [21]:
tf.zeros(shape = (3,4)) # passing in the shape as the rows adn columnsof the array that we want 
#very simialr to numpy so we are able to convert numpy arrays into tensorflow tensors 

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [22]:
#importing numpy and then coverting numpy arrays into tensorflow tensors 
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) # create a Numpy array between 1 and 25 and we need to define the data type which is integer of typ 32 
numpy_A # arrays are often noted with capital letters 

# X = tf.constant(some_matrix) # capital for matrix or tensor 
# y = tf.constnat(vector) # non-capital for vector 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [23]:
# now we want to convert numpy arrays into tenors
# the main difference between these two is that tensors can be run on a GPU much faster 
A = tf.constant(numpy_A)# we are converting it to a different shape
B = tf.constant(numpy_A, shape = (3,8))
A, B
# anyhitng iwth a numpy we are able to pass into a tensor function
# we can only select elements that are supported so the values in teh tensor shaoe argunent in constant needs specific shape values for paticular arrangement 


(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [24]:
A.ndim


1

In [25]:
B.ndim

2

In [26]:
tf.size(A)
tf.size(B)
#this is chekcing the total number of items in a tensor
#the numpy output is the size 

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [27]:
#create a rank 4 tensor
rand_4_tensor = tf.zeros(shape = [2,3,4,5])
rand_4_tensor
#creating a tensor that consisits of all zeros that contains 

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [28]:
rand_4_tensor[0]
#getting the 0th element of the tensor   
#notice the tensor changes becasue we are gettinh 

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [29]:
rand_4_tensor.shape,rand_4_tensor.ndim, tf.size(rand_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [30]:

print("number of dimensions(rank):", rand_4_tensor.ndim)
print("shape of tensor:", rand_4_tensor.shape)
print("number of elememts along the 0 axis:", rand_4_tensor.shape[0])
print("number of elements along the 1st axis:", rand_4_tensor.shape[-1])
print("total number of elements in out tensor:", tf.size(rand_4_tensor))
print("total number of elements in out tensor:", tf.size(rand_4_tensor).numpy())

number of dimensions(rank): 4
shape of tensor: (2, 3, 4, 5)
number of elememts along the 0 axis: 2
number of elements along the 1st axis: 5
total number of elements in out tensor: tf.Tensor(120, shape=(), dtype=int32)
total number of elements in out tensor: 120


In [31]:
some_list = [2,21,12,3]
some_list[:2]
# here we have an array and we want to get the fisrt 2 items of that array we use the :n function and use 2 as n

[2, 21]

In [32]:
#indexing tensors 
#tensors can be indexed just like python lists 
#if we want to get the first 2 element 
rand_4_tensor[:2,:2,:2,:2]
# here we are getting the first 2 items of every tensor array 




<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [33]:
#get the first element form each dimension from each index except for the final one and
rand_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [34]:
#lets add an extra dimensison
#create a rank 2 tensor 
rank_2_tensor = tf.constant([[2,2],
                            [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [35]:
#addin in an extra dimension ot out rank 2 tensor 
rand_3_tensor = rank_2_tensor[...,tf.newaxis] #instead of doing [:,:,:, tf.newaxis] we can use the term [...] for the previous axies 
rand_3_tensor 

#tf.newaxis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [36]:
#alternative to tf.newaxis 
tf.expand_dims(rank_2_tensor, axis = -1) 

# this means we are expanding along the final axis which is refered to by -1 which is the last axis 



<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [37]:
tf.expand_dims(rank_2_tensor, axis = 0) 
#if we get an expansion of the 0th axis we are going to get a differnet expansions 
rank_2_tensor 


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[2, 2],
       [3, 4]], dtype=int32)>

In [38]:
##manipulating tensors (tensor operations)
#you can add caues to a tensor isong teh addition operator
tensor = tf.constant([[10,7], 
                      [3,4]])
tensor + 10


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [39]:
#notice that the origional tensor is unchanged 
# if we say taht:
tensor = tensor+ 10 
tensor
#this will reuslt in the tensors values being rewritten 


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [40]:
#element operations 
# we are able to use tensorflow builtin functions to carry out the same examples 
tf.multiply(tensor, 10) # where the alias is the multiply 
#if we use the tf. ..... versions of the function we will be able to spped up operations raother than coding out tensor*10
tf.add(tensor, 3)



<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[23, 20],
       [16, 17]], dtype=int32)>

In [41]:
#matrix multiplications are one of teh omst common operations 
#matrix multiplication is when you are multiplying matricies 
#to multiply tensors we need to do the dot product 
#this is where we multiply matching members 
tf.matmul(tensor, tensor) # we dont need the full 


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [42]:
# given a certain matrix recreate in TF
tensor_A = tf.constant([[1,2,5], 
                        [7,2,1], 
                        [3,3,3]])
tensor_B = tf.constant([[3,5],
                        [6,7],
                        [1,8]])
tf.matmul(tensor_A, tensor_B)


<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[20, 59],
       [34, 57],
       [30, 60]], dtype=int32)>

In [43]:
# if we wanted to do matrix multiplication with a python operator 
tensor @ tensor # the @ symbolos for matrix multiplication in python 


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [44]:
# create 2 tensors with different shapes and multiply them  
tensor_C = tf.constant([[1,2],
                        [3,4],
                        [5,6]])
tensor_D = tf.constant([[7,8],
                        [9,10],
                        [11,12]])
tf.matmul(tensor_C, tensor_D)

# we are going to get the error "Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]""
# we can't do this because thre ar erules that matrix and tensors need to follow 
# there are 2 rules that need to be fufilled in order to be complete the muliplication
# 1) the inner dimensions must match
# 2) the resulting matrix has the shape of the outer dimensions
# how can we get the immer dimensions to match?
# we can rearrange the matrix?
# we need to change the shape of one of the matricies 



InvalidArgumentError: Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul]

In [ ]:

tensor_reshaped_D = tf.reshape(tensor_D, shape=(2,3)) # we are changing the shaep of the matrix so that it is now 2,3 
# now we taking tensor 2 and changing it from a 3, 2 to a 2, 3 tensor 
# now notice that the tensor is in 2, 3 shape and this will enable us to multiply array C by array D 

tensor_reshaped_D 

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# we are multiplying c by reshaped D  becasue now the inner dimensiosn match now becase they are both 2
tensor_C @ tensor_reshaped_D
#umltiplied the matrices using the python method  

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
#now we are multiplying the arrays C and D 
tf.matmul(tensor_reshaped_D,tensor_C)
# remember that the resulting  output is dependent on the manipulation of what ever matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 76, 100],
       [103, 136]], dtype=int32)>

In [ ]:
# transpose is another useful tensor function which is slightly different to a tensor function
tensor_C, tf.reshape(tensor_C, shape = (2,3)),tf.transpose(tensor_C)


(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 2, 3],
        [4, 5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>)

In [ ]:
# ry matrix multiplication with transpose rather than reshape 
tf.matmul(tf.transpose(tensor_C), tensor_D)
# the output is different eto the previous reshaped C matrix multiplication with tensor_D because transposition causes the reshaping of the axies 

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

** the dot product **    

In [ ]:
# we want to preform the dot product on the tensor_C and tensor_Y requires C and D to be tranposed
tf.tensordot(tf.transpose(tensor_C), tensor_D, axes = 1) # we are changingn along the first axis 
# tf.tensordot(thensor contraction of products within the argument along a paticular axes )


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# we want to tranpose along D and reshape D
tf.matmul(tensor_C, tf.transpose(tensor_D))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
# now we want to preform mutiplicatio between tensor _C and tensor_D(reshaped)
tf.matmul(tensor_C, tf.reshape(tensor_D, shape = (2, 3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

notice that we are getting different results between transpose and reshape functions 


In [ ]:
print("normal tensor_D:")
print(tensor_D, "\n")

print("tensor_D reshaped to (2,3):")
print(tf.reshape((tensor_D), shape = (2,3)),  "\n")

print("tensor_D transposed:")
print(tf.transpose(tensor_D))




normal tensor_D:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

tensor_D reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

tensor_D transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
tf.matmul(tensor_C, tf.transpose(tensor_D))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

 generally when preforming matrix multimplication on 2 axies and when teh axies dont lig up will will transpose one of the matricies to satiesfy the rules and then multiply the tensors 

In [ ]:
# if we have to change the data type of a tensor 
# the default data type of most tensors are int 32 
# create a new tensor with a default datatype (float32)

B = tf.constant([1.3,1.4])
B.dtype 

# the default datat type will depend on the type of data in the tensor


tf.float32

In [ ]:
C = tf.constant([34,223,32])
C.dtype
# notice that there is a different data type 

tf.int32

In [ ]:
# if we want to change from type 32 to 16 data type then this is called reduced precision 
# this is when there is lower precision but same accuracy 
D = tf.cast(B, dtype = tf.float16)
D, D.dtype
# now we are getting faster processing because we are using less memory (half as much)

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.3, 1.4], dtype=float16)>,
 tf.float16)

In [ ]:
# now if we want to change from float 16 to float 32
E = tf.cast(D, dtype = tf.float32)
E
# now we are getting a float 32 type data type 

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1.2998047, 1.4003906], dtype=float32)>

Aggregating tensors 


In [ ]:
#Aggregating tensors requires the condensing the tensors from multiple values down to a smaller amount of values
# get the absolute calues condensing
D = tf.constant([-7,-10])
D 
#if we want to get the absolute values we use the tf.abs(tensorname)
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

Lets go through the following forms of aggregation 
- getting the maxium
- getting the minimum
- getting the sum 
- getting the mean 


In [ ]:
# getting the mean of a tensor we use the function tf.reduce_mean()
tf.reduce_mean(D)

<tf.Tensor: shape=(), dtype=int32, numpy=-8>

In [ ]:
# lets create a new tensor 
F = tf.constant(np.random.randint(0,100,size = 50))
F

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([59, 76, 88, 58, 93, 24, 16, 53, 79, 92, 69, 86, 31, 52, 67, 63,  9,
       62, 72, 38, 36, 22, 86,  6, 58, 60, 17, 49, 88, 21, 51, 49, 77, 22,
       88, 45, 24, 26,  6, 70, 98, 30, 40, 76,  4, 68, 33, 13, 91,  6])>

In [ ]:
tf.reduce_min(F),tf.reduce_max(F), tf.reduce_sum(F), tf.reduce_mean(F),

(<tf.Tensor: shape=(), dtype=int64, numpy=4>,
 <tf.Tensor: shape=(), dtype=int64, numpy=98>,
 <tf.Tensor: shape=(), dtype=int64, numpy=2547>,
 <tf.Tensor: shape=(), dtype=int64, numpy=50>)

What if we want to find the varience and the standard deviation in a tensor?


In [ ]:
# in order to use the varience function we need to import tensorflow probability 

import tensorflow_probability as tfp
tfp.stats.variance(F)
tf.math.reduce_std(tf.cast(F, dtype = tf.float32))
                   # notice that to get the standard deviation we need to cast the tensor to float32 type 
#there is another way to get the varience 
tf.math.reduce_variance(tf.cast(F, dtype = tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.308725>

Find the positional maximum and minimum



In [6]:
tf.random.set_seed(42)
with tf.device('/cpu:0'): G = tf.random.uniform(shape=[50])
G 
# we need to run the function in the tf.device 


<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [15]:
# to find the postiional maximum 
tf.argmax(G)


<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [14]:
# now we are indexing on our largest value 
G[tf.argmax(G)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [16]:
# findignn the max vlue of G 
tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [13]:
#checking for eqality indexing
G[tf.argmax(G)] == tf.reduce_max(G)

<tf.Tensor: shape=(), dtype=bool, numpy=True>

In [18]:
# finding the positional minimum 
tf.argmin(G)


<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [19]:
# now we want to get the index 
G[tf.argmin(G)]
# this will return the value at that index 

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

In [21]:
# now we need to find the minimum using the positional minimum index
G[tf.argmin(G)] == tf.reduce_min(G)

# this returns true which will validate that there is a minimum at this positon because the tf.reduce_min will return the minimum and we are comparieng both and will return true if they are the same 

<tf.Tensor: shape=(), dtype=bool, numpy=True>