In [23]:
import tensorflow as tf   
import numpy as np 
print(tf.__version__)
print(np.__version__)


2.9.2
1.22.3


In [24]:
# creating a tensor 

scalar = tf.constant(7)
scalar
# testing scalars


<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [25]:
#checking the number of dimensions 
scalar.ndim
## this will show 0 becasue there are no dimensions in a scalar with only 1 dimension


0

In [26]:
vector = tf.constant([10,10])
vector 

#here we are making a vector with the 10 ad 10 compoenents then are printing the componenets

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [27]:
#checking the numeber of dimensions that are present in the vector

vector.ndim
# we are getting 1 as the number of dimensions because we see that there is only 1 dimension in a vector  with 2 compoenents 

1

In [28]:
matrix = tf.constant([[10,7],
                    [7,10]])
matrix
# creating a tensor matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [29]:
# we are now chekcing the number of dimensions
matrix.ndim
## notice we are getting 2 as the number of dimensions for a matrix 

2

In [30]:
# creating another matrix that has datatype defined 

matrix2 = tf.constant([[10.,7.],
                       [3.,2.],
                       [8.,9.]], dtype = tf.float16) # specifying the datat type 
matrix2
# initially we are printing out the number of shapes (rows, columns) and tehn the datat type which is float type in this canse )

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  2.],
       [ 8.,  9.]], dtype=float16)>

In [31]:
# the numeber of dimensions of our matrix would be still 2 because it is the total number of elements in the shape matrix
matrix2.ndim

2

In [32]:
## a tensor hads 3 dimensions 
tensor = tf.constant([[[1,2,3,],[4,5,6]],
                      [[7,8,9],[10,11,12]],
                      [[13,14,15],[16,17,18]]])
tensor
#now there is a new element in shape 

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [33]:
tensor.ndim
 

3

In [34]:
# we are able to use tf.variable to create a tensor of the same
# we want to create teh same tensor as the tensor above 
changable_tensor = tf.Variable([10,7])
unchangable_tensor = tf.constant([10,7])
changable_tensor,unchangable_tensor
#the output will be the same but the variable will be 0 in the changalbe tensor because we are able to change the variable  


(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [35]:
# we want to change the element in the 0th posisiton 
# then we can use the .assign() function to change the value 
changable_tensor[0].assign(7)
changable_tensor

# now we have changed the value so the tensor reads [7,7]
# we are not able to change the values in the constant tensors 
#generally we want to use constant tensors

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [36]:
# creating random tensors 
# these are tensors tensors that are of abitrary size which contain random numbers 
# this might be done in the scenario of a neural netowrk it will initilize a neurla network with random number s and then as it learns it will change the random tensors in order to change the weightings 
with tf.device('/cpu:0'): randomtensor1 = tf.random.Generator.from_seed(7) # the seed for reproducibility 
randomtensor1 = randomtensor1.normal(shape=(3, 2))
randomtensor1


<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [37]:
with tf.device('/cpu:0'): randomtensor2 = tf.random.Generator.from_seed(7)
randomtensor2 = randomtensor2.normal(shape=(3,2)) # generates numbers fomr a normal distribution
randomtensor2

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.3240396 ,  0.28785667],
       [-0.8757901 , -0.08857018],
       [ 0.69211644,  0.84215707]], dtype=float32)>

In [38]:
randomtensor1 == randomtensor2
# now we are chekcing if 2 different tensors are equal 
# we can use the == operater to check this 
#wehn we set the seed we essetially modify the random numbers with the certain seed 
#if we change teh seed we will get different value 




<tf.Tensor: shape=(3, 2), dtype=bool, numpy=
array([[ True,  True],
       [ True,  True],
       [ True,  True]])>

In [39]:
# how to shuffle the order of teh elements in a tensor
# shuffle tensor so that the inherent order doesnt affect the tensor 
not_shuffled = tf.constant([[10,7],
                            [3,4],
                            [8,9]],)
not_shuffled.ndim

2

In [40]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 8,  9]], dtype=int32)>

In [41]:
tf.random.set_seed(42)# the operation level seed #now if we set the seed first and then we are going to affect the behaviour of the tensor so ts certain 
shuffled = tf.random.shuffle(not_shuffled, seed = 3) #this contains the operation level seed
shuffled
# shuffling the tensor along the first dimension
#what if we want to shuffle along the second dimension ?
# what happens when we shuffle seeds is that we are going to 
# if both the global and operation level seeds are set then theya re used in conjucntion 
# if we want our shuffled tensors we have to use the global level random seed 
# to make reproducable experiments we may use random seeds and set them to enable reproducable randomness 

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 8,  9],
       [ 3,  4]], dtype=int32)>

In [42]:
#numpy ones is a way to make tensors 
# we are able to use the tf.ones method to create a tensor that consisitas of all float type ones 
tf.ones([10,4])



<tf.Tensor: shape=(10, 4), dtype=float32, numpy=
array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)>

In [43]:
tf.zeros(shape = (3,4)) # passing in the shape as the rows adn columnsof the array that we want 
#very simialr to numpy so we are able to convert numpy arrays into tensorflow tensors 

<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]], dtype=float32)>

In [44]:
#importing numpy and then coverting numpy arrays into tensorflow tensors 
import numpy as np
numpy_A = np.arange(1,25, dtype = np.int32) # create a Numpy array between 1 and 25 and we need to define the data type which is integer of typ 32 
numpy_A # arrays are often noted with capital letters 

# X = tf.constant(some_matrix) # capital for matrix or tensor 
# y = tf.constnat(vector) # non-capital for vector 


array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [45]:
# now we want to convert numpy arrays into tenors
# the main difference between these two is that tensors can be run on a GPU much faster 
A = tf.constant(numpy_A)# we are converting it to a different shape
B = tf.constant(numpy_A, shape = (3,8))
A, B
# anyhitng iwth a numpy we are able to pass into a tensor function
# we can only select elements that are supported so the values in teh tensor shaoe argunent in constant needs specific shape values for paticular arrangement 


(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(3, 8), dtype=int32, numpy=
 array([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16],
        [17, 18, 19, 20, 21, 22, 23, 24]], dtype=int32)>)

In [46]:
A.ndim


1

In [47]:
B.ndim

2

In [48]:
tf.size(A)
tf.size(B)
#this is chekcing the total number of items in a tensor
#the numpy output is the size 

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [52]:
#create a rank 4 tensor
rand_4_tensor = tf.zeros(shape = [2,3,4,5])
rand_4_tensor
#creating a tensor that consisits of all zeros that contains 

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [54]:
rand_4_tensor[0]
#getting the 0th element of the tensor   
#notice the tensor changes becasue we are gettinh 

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [57]:
rand_4_tensor.shape,rand_4_tensor.ndim, tf.size(rand_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [62]:

print("number of dimensions(rank):", rand_4_tensor.ndim)
print("shape of tensor:", rand_4_tensor.shape)
print("number of elememts along the 0 axis:", rand_4_tensor.shape[0])
print("number of elements along the 1st axis:", rand_4_tensor.shape[-1])
print("total number of elements in out tensor:", tf.size(rand_4_tensor))
print("total number of elements in out tensor:", tf.size(rand_4_tensor).numpy())

number of dimensions(rank): 4
shape of tensor: (2, 3, 4, 5)
elememts along the 0 axis: 2
elements along the 1 axis: 5
total number of elements in out tensor: tf.Tensor(120, shape=(), dtype=int32)
total number of elements in out tensor: 120


In [66]:
some_list = [2,21,12,3]
some_list[:2]
# here we have an array and we want to get the fisrt 2 items of that array we use the :n function and use 2 as n

[2, 21]

In [67]:
#indexing tensors 
#tensors can be indexed just like python lists 
#if we want to get the first 2 element 
rand_4_tensor[:2,:2,:2,:2]
# here we are getting the first 2 items of every tensor array 




<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [71]:
#get the first element form each dimension from each index except for the final one and
rand_4_tensor[:1, :1, :1, :]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [74]:
#lets add an extra dimensison
#create a rank 2 tensor 
rank_2_tensor = tf.constant([[2,2],
                            [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [75]:
#addin in an extra dimension ot out rank 2 tensor 
rand_3_tensor = rank_2_tensor[...,tf.newaxis] #instead of doing [:,:,:, tf.newaxis] we can use the term [...] for the previous axies 
rand_3_tensor 

#tf.newaxis

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[2],
        [2]],

       [[3],
        [4]]], dtype=int32)>

In [ ]:
#alternative to tf.newaxis 
tf.expand.dims()